{
    "columns": {
        "wdir": {
            "id": "wdir",
            "name": "Wind Direction",
            "type": 2,
            "unit": null
        },
        "uvindex": {
            "id": "uvindex",
            "name": "weather_uvindex",
            "type": 2,
            "unit": null
        },
        "latitude": {
            "id": "latitude",
            "name": "Latitude",
            "type": 2,
            "unit": null
        },
        "preciptype": {
            "id": "preciptype",
            "name": "weather_preciptype",
            "type": 1,
            "unit": null
        },
        "cin": {
            "id": "cin",
            "name": "weather_cin",
            "type": 2,
            "unit": null
        },
        "cloudcover": {
            "id": "cloudcover",
            "name": "Cloud Cover",
            "type": 2,
            "unit": null
        },
        "pop": {
            "id": "pop",
            "name": "Chance Precipitation (%)",
            "type": 2,
            "unit": null
        },
        "mint": {
            "id": "mint",
            "name": "Minimum Temperature",
            "type": 2,
            "unit": "degC"
        },
        "datetime": {
            "id": "datetime",
            "name": "Date time",
            "type": 3,
            "unit": null
        },
        "precip": {
            "id": "precip",
            "name": "Precipitation",
            "type": 2,
            "unit": "mm"
        },
        "solarradiation": {
            "id": "solarradiation",
            "name": "Solar Radiation",
            "type": 2,
            "unit": null
        },
        "dew": {
            "id": "dew",
            "name": "Dew Point",
            "type": 2,
            "unit": "degc"
        },
        "humidity": {
            "id": "humidity",
            "name": "Relative Humidity",
            "type": 2,
            "unit": null
        },
        "longitude": {
            "id": "longitude",
            "name": "Longitude",
            "type": 2,
            "unit": null
        },
        "temp": {
            "id": "temp",
            "name": "Temperature",
            "type": 2,
            "unit": "degc"
        },
        "address": {
            "id": "address",
            "name": "Address",
            "type": 1,
            "unit": null
        },
        "maxt": {
            "id": "maxt",
            "name": "Maximum Temperature",
            "type": 2,
            "unit": "degC"
        },
        "visibility": {
            "id": "visibility",
            "name": "Visibility",
            "type": 2,
            "unit": "km"
        },
        "wspd": {
            "id": "wspd",
            "name": "Wind Speed",
            "type": 2,
            "unit": "kph"
        },
        "severerisk": {
            "id": "severerisk",
            "name": "weather_severerisk",
            "type": 2,
            "unit": null
        },
        "solarenergy": {
            "id": "solarenergy",
            "name": "Solar Energy",
            "type": 2,
            "unit": null
        },
        "resolvedAddress": {
            "id": "resolvedAddress",
            "name": "Resolved Address",
            "type": 1,
            "unit": null
        },
        "heatindex": {
            "id": "heatindex",
            "name": "Heat Index",
            "type": 2,
            "unit": "degc"
        },
        "snowdepth": {
            "id": "snowdepth",
            "name": "Snow Depth",
            "type": 2,
            "unit": "cm"
        },
        "sealevelpressure": {
            "id": "sealevelpressure",
            "name": "Sea Level Pressure",
            "type": 2,
            "unit": "mb"
        },
        "snow": {
            "id": "snow",
            "name": "Snow",
            "type": 2,
            "unit": "cm"
        },
        "name": {
            "id": "name",
            "name": "Name",
            "type": 1,
            "unit": null
        },
        "wgust": {
            "id": "wgust",
            "name": "Wind Gust",
            "type": 2,
            "unit": "kph"
        },
        "conditions": {
            "id": "conditions",
            "name": "Conditions",
            "type": 1,
            "unit": null
        },
        "windchill": {
            "id": "windchill",
            "name": "Wind Chill",
            "type": 2,
            "unit": "degc"
        },
        "cape": {
            "id": "cape",
            "name": "weather_cape",
            "type": 2,
            "unit": null
        }
    },
    "remainingCost": 0,
    "queryCost": 1,
    "messages": null,
    "location": {
        "stationContributions": null,
        "values": [
            {
                "wdir": 167.9,
                "uvindex": 0.0,
                "datetimeStr": "2023-02-19T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 1.5,
                "pop": 0.0,
                "mint": 23.4,
                "datetime": 1676766600000,
                "precip": 0.0,
                "solarradiation": 0.0,
                "dew": 1.2,
                "humidity": 22.8,
                "temp": 23.8,
                "maxt": 24.2,
                "visibility": 24.1,
                "wspd": 9.5,
                "severerisk": 10.0,
                "solarenergy": 0.0,
                "heatindex": null,
                "snowdepth": 0.0,
                "sealevelpressure": 1013.3,
                "snow": 0.0,
                "wgust": 10.4,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 244.1,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-20T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 13.7,
                "pop": 0.0,
                "mint": 20.1,
                "datetime": 1676853000000,
                "precip": 0.0,
                "solarradiation": 246.6,
                "dew": -2.6,
                "humidity": 16.0,
                "temp": 26.9,
                "maxt": 36.1,
                "visibility": 24.1,
                "wspd": 8.9,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 33.2,
                "snowdepth": 0.0,
                "sealevelpressure": 1011.0,
                "snow": 0.0,
                "wgust": 21.6,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 260.2,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-21T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 36.1,
                "pop": 0.0,
                "mint": 19.8,
                "datetime": 1676939400000,
                "precip": 0.0,
                "solarradiation": 249.3,
                "dew": -3.8,
                "humidity": 14.5,
                "temp": 26.3,
                "maxt": 35.2,
                "visibility": 24.1,
                "wspd": 12.0,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 32.4,
                "snowdepth": 0.0,
                "sealevelpressure": 1010.8,
                "snow": 0.0,
                "wgust": 31.3,
                "conditions": "Partially cloudy",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 256.4,
                "uvindex": 2.3,
                "datetimeStr": "2023-02-22T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 66.8,
                "pop": 0.0,
                "mint": 20.4,
                "datetime": 1677025800000,
                "precip": 0.0,
                "solarradiation": 230.5,
                "dew": 2.7,
                "humidity": 23.0,
                "temp": 26.1,
                "maxt": 33.9,
                "visibility": 24.1,
                "wspd": 9.2,
                "severerisk": 10.0,
                "solarenergy": 0.8,
                "heatindex": 31.4,
                "snowdepth": 0.0,
                "sealevelpressure": 1010.5,
                "snow": 0.0,
                "wgust": 20.2,
                "conditions": "Partially cloudy",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 265.4,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-23T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 36.7,
                "pop": 0.0,
                "mint": 20.1,
                "datetime": 1677112200000,
                "precip": 0.0,
                "solarradiation": 245.9,
                "dew": 2.8,
                "humidity": 23.9,
                "temp": 25.7,
                "maxt": 32.8,
                "visibility": 24.1,
                "wspd": 9.6,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 30.4,
                "snowdepth": 0.0,
                "sealevelpressure": 1010.5,
                "snow": 0.0,
                "wgust": 18.7,
                "conditions": "Partially cloudy",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 263.6,
                "uvindex": 2.8,
                "datetimeStr": "2023-02-24T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 40.0,
                "pop": 0.0,
                "mint": 19.4,
                "datetime": 1677198600000,
                "precip": 0.0,
                "solarradiation": 270.1,
                "dew": 2.6,
                "humidity": 23.8,
                "temp": 25.3,
                "maxt": 32.0,
                "visibility": 24.1,
                "wspd": 8.2,
                "severerisk": 10.0,
                "solarenergy": 1.0,
                "heatindex": 29.8,
                "snowdepth": 0.0,
                "sealevelpressure": 1011.8,
                "snow": 0.0,
                "wgust": 15.1,
                "conditions": "Partially cloudy",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 198.6,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-25T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 6.3,
                "pop": 0.0,
                "mint": 20.0,
                "datetime": 1677285000000,
                "precip": 0.0,
                "solarradiation": 249.3,
                "dew": 1.5,
                "humidity": 21.0,
                "temp": 25.9,
                "maxt": 32.5,
                "visibility": 24.1,
                "wspd": 5.2,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 30.2,
                "snowdepth": 0.0,
                "sealevelpressure": 1012.5,
                "snow": 0.0,
                "wgust": 10.4,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 99.8,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-26T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 0.0,
                "pop": 0.0,
                "mint": 20.2,
                "datetime": 1677371400000,
                "precip": 0.0,
                "solarradiation": 251.8,
                "dew": 0.2,
                "humidity": 19.2,
                "temp": 26.0,
                "maxt": 33.1,
                "visibility": 24.1,
                "wspd": 6.1,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 30.7,
                "snowdepth": 0.0,
                "sealevelpressure": 1014.5,
                "snow": 0.0,
                "wgust": 11.9,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 134.1,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-27T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 0.1,
                "pop": 0.0,
                "mint": 21.1,
                "datetime": 1677457800000,
                "precip": 0.0,
                "solarradiation": 254.8,
                "dew": -1.8,
                "humidity": 15.9,
                "temp": 26.5,
                "maxt": 33.2,
                "visibility": 24.1,
                "wspd": 5.4,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 30.7,
                "snowdepth": 0.0,
                "sealevelpressure": 1014.0,
                "snow": 0.0,
                "wgust": 10.8,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 192.6,
                "uvindex": 2.5,
                "datetimeStr": "2023-02-28T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 0.0,
                "pop": 0.0,
                "mint": 20.5,
                "datetime": 1677544200000,
                "precip": 0.0,
                "solarradiation": 255.1,
                "dew": -2.0,
                "humidity": 15.8,
                "temp": 26.5,
                "maxt": 33.4,
                "visibility": 24.1,
                "wspd": 4.8,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 30.9,
                "snowdepth": 0.0,
                "sealevelpressure": 1012.5,
                "snow": 0.0,
                "wgust": 11.2,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 125.4,
                "uvindex": 2.5,
                "datetimeStr": "2023-03-01T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 14.9,
                "pop": 0.0,
                "mint": 20.9,
                "datetime": 1677630600000,
                "precip": 0.0,
                "solarradiation": 254.6,
                "dew": -1.8,
                "humidity": 15.0,
                "temp": 27.6,
                "maxt": 34.8,
                "visibility": 24.1,
                "wspd": 7.5,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 32.1,
                "snowdepth": 0.0,
                "sealevelpressure": 1011.6,
                "snow": 0.0,
                "wgust": 17.3,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 287.6,
                "uvindex": 2.5,
                "datetimeStr": "2023-03-02T00:30:00+05:30",
                "preciptype": "",
                "cin": -0.4,
                "cloudcover": 9.8,
                "pop": 4.8,
                "mint": 21.3,
                "datetime": 1677717000000,
                "precip": 0.0,
                "solarradiation": 256.5,
                "dew": -0.2,
                "humidity": 16.9,
                "temp": 27.5,
                "maxt": 34.2,
                "visibility": 24.1,
                "wspd": 8.2,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 31.6,
                "snowdepth": 0.0,
                "sealevelpressure": 1013.8,
                "snow": 0.0,
                "wgust": 19.4,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.5
            },
            {
                "wdir": 289.2,
                "uvindex": 2.6,
                "datetimeStr": "2023-03-03T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 0.4,
                "pop": 0.0,
                "mint": 20.6,
                "datetime": 1677803400000,
                "precip": 0.0,
                "solarradiation": 258.6,
                "dew": 1.6,
                "humidity": 20.2,
                "temp": 26.8,
                "maxt": 33.8,
                "visibility": 24.1,
                "wspd": 11.5,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 31.3,
                "snowdepth": 0.0,
                "sealevelpressure": 1015.8,
                "snow": 0.0,
                "wgust": 19.1,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 287.3,
                "uvindex": 2.6,
                "datetimeStr": "2023-03-04T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 14.1,
                "pop": 0.0,
                "mint": 19.8,
                "datetime": 1677889800000,
                "precip": 0.0,
                "solarradiation": 261.3,
                "dew": -0.7,
                "humidity": 18.3,
                "temp": 25.8,
                "maxt": 33.4,
                "visibility": 24.1,
                "wspd": 9.7,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 30.9,
                "snowdepth": 0.0,
                "sealevelpressure": 1015.1,
                "snow": 0.0,
                "wgust": 19.8,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 196.0,
                "uvindex": 2.7,
                "datetimeStr": "2023-03-05T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 1.4,
                "pop": 0.0,
                "mint": 19.7,
                "datetime": 1677976200000,
                "precip": 0.0,
                "solarradiation": 265.1,
                "dew": -1.0,
                "humidity": 17.3,
                "temp": 26.5,
                "maxt": 33.6,
                "visibility": 24.1,
                "wspd": 7.2,
                "severerisk": 10.0,
                "solarenergy": 1.0,
                "heatindex": 31.1,
                "snowdepth": 0.0,
                "sealevelpressure": 1012.6,
                "snow": 0.0,
                "wgust": 13.7,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            },
            {
                "wdir": 164.4,
                "uvindex": 2.6,
                "datetimeStr": "2023-03-06T00:30:00+05:30",
                "preciptype": "",
                "cin": 0.0,
                "cloudcover": 0.0,
                "pop": 4.8,
                "mint": 21.9,
                "datetime": 1678062600000,
                "precip": 0.0,
                "solarradiation": 263.5,
                "dew": -1.2,
                "humidity": 15.1,
                "temp": 28.3,
                "maxt": 35.2,
                "visibility": 24.1,
                "wspd": 5.5,
                "severerisk": 10.0,
                "solarenergy": 0.9,
                "heatindex": 32.5,
                "snowdepth": 0.0,
                "sealevelpressure": 1012.0,
                "snow": 0.0,
                "wgust": 9.4,
                "conditions": "Clear",
                "windchill": null,
                "cape": 0.0
            }
        ],
        "id": "kota,India",
        "address": "Kota, RJ, India",
        "name": "kota,India",
        "index": 0,
        "latitude": 25.1653,
        "longitude": 75.8512,
        "distance": 0.0,
        "time": 0.0,
        "tz": "Asia/Kolkata",
        "currentConditions": {},
        "alerts": null
    }
}
